---
- hosts: webserver
  become: true
  tasks:
    - name: install fastapi image
      shell: sudo docker pull renckel/hello-fastapi:latest

    - name: stop all containers
      shell: sudo docker stop $(sudo docker ps -q)

    - name: remove all containers
      shell: sudo docker rm $(sudo docker ps -a -q)

    - name: run fastapi container
      shell: sudo docker run --name target-project -p 80:80 -d renckel/hello-fastapi
