---
- hosts: webserver
  become: true
  tasks:
    - name: install fastapi image
      command: ["/bin/sh","-c"]
      args: ["sudo docker pull renckel/hello-fastapi:latest"]
    - name: stop all containers
      command: ["/bin/sh","-c"]
      args: ["sudo docker stop $(sudo docker ps -q)"]
    - name: remove all containers
      command: ["/bin/sh","-c"]
      args: ["sudo docker rm $(sudo docker ps -a -q)"]
    - name: run fastapi container
      command: ["/bin/sh","-c"]
      args: ["sudo docker run --name target-project -p 80:80 -d renckel/hello-fastapi"]
