---
- hosts: webserver
  become: true
  tasks:
    - name: install fastapi image
      command: sudo docker pull renckel/hello-fastapi:latest
    - name: run fastapi container
      command: docker kill $(docker ps -q)
      command: docker rm $(docker ps -a -q)
      command: sudo docker run -p 80:80 -d renckel/hello-fastapi
