---
- hosts: webserver
  become: true
  tasks:
    - name: install fastapi image
      command: sudo docker pull renckel/hello-fastapi:latest
    - name: run fastapi container
      command: sudo docker run --name target-project -p 80:80 -d renckel/hello-fastapi
