---
- hosts: webserver
  become: true
  tasks:
    - name: install fastapi image and run it
      command: ["/bin/sh", "-c"]
        args:
          - sudo docker pull renckel/hello-fastapi:latest;
            sudo docker stop $(sudo docker ps -q);
            sudo docker rm $(sudo docker ps -a -q);
            sudo docker run --name target-project -p 80:80 -d renckel/hello-fastapi;
